apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: k8s-task
  name: k8s-task
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-task
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: k8s-task
    spec:
      containers:
      - image: 062746389614.dkr.ecr.us-east-1.amazonaws.com/demo-test:latest
        name: demo-test