---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: cluster-system-anonymons
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:anonymous

---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: k8s-test
  name: k8s-test
spec:
  containers:
  - image: 062746389614.dkr.ecr.us-east-1.amazonaws.com/demo-test:latest
    name: k8s-test
  dnsPolicy: ClusterFirst
  restartPolicy: Never






