apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy_name
  labels:
    app: label_info
spec:
  replicas: 1
  selector:
    matchLabels:
      app: label_info
  template:
    metadata:
      labels:
        app: label_info
    spec:
      containers:
      - name: Testinga
        image: sample_image
        ports:
        - containerPort: 80