---
apiVersion: v1
data:
  Restart_policy: Never
  sample_image: 062746389614.dkr.ecr.us-east-1.amazonaws.com/demo-test:latest
  sample_kind: Pod
  sample_label: alpine
kind: ConfigMap
metadata:
  name: deploy
  
---
apiVersion: v1
kind: sample_kind
metadata:
  labels:
    run: sample_label
  name: sample_label
spec:
  containers:
  - image: sample_image
    name: apline
  restartPolicy: Restart_policy
