apiVersion: v1
kind: Pod
metadata:
  labels:
    run: test
  name: test
spec:
  containers:
  - image: 062746389614.dkr.ecr.us-east-1.amazonaws.com/demo-test:latest
    name: test
  dnsPolicy: ClusterFirst
  restartPolicy: Never